name: xftts_cli
description: A sample command-line application.
version: 0.1.0
homepage: https://github.com/tyrchen/xftts-cli

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  front_matter: ^1.1.0
  xftts: '>=0.1.2 <1.0.0'
  
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
